#!/usr/bin/env php
<?php

// Define Directory Sperator
define('DS', DIRECTORY_SEPARATOR);

// Define Base Dir Path
define('BASE', __DIR__ . DS);

// load Reborn CMS start file
require_once __DIR__.'/heart/reborn/src/start.php';

require_once __DIR__.'/heart/vendor/autoload.php';

use Reborn\Console\ModuleCommand;
use Reborn\Cores\Version;
use Symfony\Component\Console\Application;

$application = new Application(Version::getAppName(), Version::getVersion());
$application->add(new ModuleCommand);
$application->run();
