#!/usr/bin/env php
<?php

// Define Directory Sperator
define('DS', DIRECTORY_SEPARATOR);

// Define Base Dir Path
define('BASE', __DIR__ . DS);

date_default_timezone_set('UTC');

/**
 * ---------------------------------------------------------
 * Load Reborn's sites manager file
 * ---------------------------------------------------------
 *
 * Reborn define other constants for application,
 * start timer and memory record for profiling and
 * make class alias to easy access for developer.
 *
 */
$sites = require __DIR__.'/content/sites.php';

/**
 * ---------------------------------------------------------
 * Load Reborn's start helper file
 * ---------------------------------------------------------
 *
 * Reborn define other constants for application,
 * start timer and memory record for profiling and
 * make class alias to easy access for developer.
 *
 */
require_once __DIR__.'/heart/reborn/src/start.php';

$commands = require __DIR__.'/content/commands/register.php';

/**
 * ---------------------------------------------------------
 * Now Create the Reborn Application Instance.
 * ---------------------------------------------------------
 *
 * Create Reborn Application Object to start the application.
 *
 */
$reborn = new Reborn\Cores\Application();

$application = new Reborn\Console\Application(Reborn\Cores\Version::getAppName(), Reborn\Cores\Version::getVersion());
$application->setRebornApplication($reborn);
$application->registerForReborn();
$application->addCommands($commands);
$application->run();
